<div id="menu">
		<p><a href="../index.php">HOME</a></p>

		<p><strong>Lab Assignments</strong></p>
		<ul>
		<li><a href="../lab1/lab1.php">Assignment 1</a></li>
		<li><a href="lab2/lab2.php">Assignment 2</a></li>
		<li><a href="lab3/lab3.php">Assignment 3</a></li>
		<li><a href="lab4/lab4.php">Assignment 4</a></li>
		</ul>

		<p><strong>Lab Practica</strong></p>
		<ul>
		<li><a href="prac1/prac1.php">Practicum 1</a></li>
		<li><a href="prac2/prac2.php">Practicum 2</a></li>
		</ul>
		</div>